---
- name: Restart ufw
  service:
    name: ufw
    state: restarted
    enabled: yes
  become: true

- name: Redis Restart
  service:
    name: redis
    state: restarted
    enabled: yes
  become: true